/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Image;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.*;


/**
 *
 * @author Shubh's PC
 */



public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
  
   
    
    
    public MainJFrame() {
        initComponents();
       
      
       
          
        
    }

     Connection con ;
     PreparedStatement ps;
     ResultSet rs;
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jUserTypecombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jlogin = new javax.swing.JButton();
        jreg = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jCheckpass = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(186, 79, 84));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Password:");

        jUsername.setBackground(new java.awt.Color(186, 79, 84));
        jUsername.setForeground(new java.awt.Color(0, 0, 0));
        jUsername.setText("Enter Username");
        jUsername.setBorder(null);
        jUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jUsernameMousePressed(evt);
            }
        });

        jUserTypecombo.setBackground(new java.awt.Color(255, 255, 255));
        jUserTypecombo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jUserTypecombo.setForeground(new java.awt.Color(0, 0, 0));
        jUserTypecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Patient", "Doctor", "Admin", "Community Admin", "Hospital Admin" }));
        jUserTypecombo.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("User Type:");

        jlogin.setBackground(new java.awt.Color(255, 255, 255));
        jlogin.setForeground(new java.awt.Color(0, 0, 0));
        jlogin.setText("Login ");
        jlogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });

        jreg.setBackground(new java.awt.Color(255, 255, 255));
        jreg.setForeground(new java.awt.Color(0, 0, 0));
        jreg.setText("Register");
        jreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jregActionPerformed(evt);
            }
        });

        jPassword.setBackground(new java.awt.Color(186, 79, 84));
        jPassword.setForeground(new java.awt.Color(0, 0, 0));
        jPassword.setText("password");
        jPassword.setBorder(null);
        jPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordMousePressed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        jCheckpass.setBackground(new java.awt.Color(186, 79, 84));
        jCheckpass.setText("Show Password");
        jCheckpass.setBorder(null);
        jCheckpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckpassActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jCheckpass))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jlogin)
                        .addGap(46, 46, 46)
                        .addComponent(jreg, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(jPassword)
                            .addComponent(jUserTypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserTypecombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckpass)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlogin)
                    .addComponent(jreg))
                .addContainerGap(377, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(74, 31, 61));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsernameMousePressed
        // TODO add your handling code here:
         jUsername.setText("");
    }//GEN-LAST:event_jUsernameMousePressed

    private void jPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordMousePressed
        // TODO add your handling code here:
        jPassword.setText("");
    }//GEN-LAST:event_jPasswordMousePressed

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
        // TODO add your handling code here:
        
        String ur = jUsername.getText();
        String pass = jPassword.getText();
        String ut = jUserTypecombo.getSelectedItem().toString();
      
           
        if (ur.equals("") || pass.equals("") || ut.equals("Select"))
       {
                 
          JOptionPane.showMessageDialog(rootPane, "please enter all fields ");        
        }
        else {
            
                     
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/aed","root","root");
                
                
                 if(ut.equals("Patient"))
                {  
                   String qry ="Select * from patient_info where username=? and password=? ";
                ps =con.prepareStatement(qry);
                ps.setString(1,ur);
                ps.setString(2, pass);
                rs = ps.executeQuery();
                if(rs.next())
                {                                    
                    Patient_panel pn =new Patient_panel();
     
                    pn.addinfo(ur,pass);
                    pn.setVisible(true);
                    dispose(); 
                }
                else {    
                    JOptionPane.showMessageDialog(rootPane, "please enter correct username and password!!! ");   
                }
                 
                }
                 else if(ut.equals("Doctor"))
                {   
                    String qry1 ="select * from doctor_directory where docid=? and password=?";
                ps =con.prepareStatement(qry1);
                ps.setString(1,ur);
                ps.setString(2, pass);
                rs = ps.executeQuery();
                     
                if(rs.next())
                {
                                                         
                    doctor_panel dp =new doctor_panel();
                    dp.getdname(ur);
                    dp.setVisible(true);
                    dispose();
                }
                else {
                    
                    JOptionPane.showMessageDialog(rootPane, "please enter correct username and password!!! "); 
                    
                }
    
                }
                  else if(ut.equals("Admin"))
                {   
                    String qry1 ="select * from admin where username=? and pass=?";
                ps =con.prepareStatement(qry1);
                ps.setString(1,ur);
                ps.setString(2, pass);
                rs = ps.executeQuery();
                     
                if(rs.next())
                {
                                                         
                    Admin ad =new Admin();
                    ad.setVisible(true);
                    dispose();
                }
                else {
                    
                    JOptionPane.showMessageDialog(rootPane, "please enter correct username and password!!! "); 
                    
                }
    
                }
                 else if(ut.equals("Hospital Admin"))
                {   
                    String qry1 ="select * from Hos_adm where HsAdm_id=? and pass=?";
                ps =con.prepareStatement(qry1);
                ps.setString(1,ur);
                ps.setString(2, pass);
                rs = ps.executeQuery();
                     
                if(rs.next())
                {
                                                         
                    Hos_adm ham = new Hos_adm();
                    ham.setVisible(true);
                    dispose();
                }
                else {
                    
                    JOptionPane.showMessageDialog(rootPane, "please enter correct username and password!!! "); 
                    
                }
    
                }
                
                
                
                
                
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
             
                 
        
            
        }
               
        
    }//GEN-LAST:event_jloginActionPerformed

    private void jregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregActionPerformed
        // TODO add your handling code here:
 
        
        
           
            String ut1 = jUserTypecombo.getSelectedItem().toString();
            
                if(ut1.equalsIgnoreCase("Select"))
                {
                     JOptionPane.showMessageDialog(this,
                "If You are a new user then select User Type and Press register button",
                " Error",
                JOptionPane.INFORMATION_MESSAGE);
                }
                else if(ut1.equalsIgnoreCase("patient"))
                {
                   Patient_reg pd = new Patient_reg();
                
                    pd.setVisible(true);
                     dispose();
                }
        
          //  Registration rg =new Registration();
          //  rg.setVisible(true);
          
          
       
    }//GEN-LAST:event_jregActionPerformed

    private void jCheckpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckpassActionPerformed
        // TODO add your handling code here:
        if (jCheckpass.isSelected())
        {
           jPassword.setEchoChar((char)0);
        }
        else {
            jPassword.setEchoChar('*');
        }
        
        
    }//GEN-LAST:event_jCheckpassActionPerformed
   
    
  
    public void doclogin( ) throws SQLException
    {
        
    }
            
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckpass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox<String> jUserTypecombo;
    private javax.swing.JTextField jUsername;
    private javax.swing.JButton jlogin;
    private javax.swing.JButton jreg;
    // End of variables declaration//GEN-END:variables
}
